[package]
name = "sust-server"
version = "0.1.0"
authors = ["Connor Roizman", "Jeff Putlock"]
edition = "2021"
rust-version = "1.63"
repository = "https://github.com/connorjayr/sust"
publish = false

[dependencies]
actix-files = "0.6"
actix-web = "4"
env_logger = "0.9"
